name: test_task
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependency_overrides:
  mobx:
    git:
      url: https://github.com/altynbek132/mobx.dart
      path: mobx

dependencies:
  flutter:
    sdk: flutter

  # ===================================================== MY UTILS =======================================================

  utils:
    git:
      url: https://github.com/altynbek132/flutter_util_packages
      path: packages/utils
  # ! overridden
  mobx: any
  flutter_mobx:
    git:
      url: https://github.com/altynbek132/mobx.dart
      path: flutter_mobx
  elementary:
    git:
      url: https://github.com/altynbek132/flutter-elementary
      path: packages/elementary
  disposing:
    git:
      url: https://github.com/altynbek132/dart_disposing
      path: packages/disposing
  awesome_extensions:
    git:
      url: https://github.com/altynbek132/awesome_extensions

  logger: ^2.5.0
  get_it: ^7.7.0
  injectable: ^2.5.0
  provider: ^6.1.2
  collection: ^1.19.0
  rxdart: ^0.27.7
  meta: ^1.15.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  retrofit: ^4.4.2
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.20.1

# ================================================= DEV DEPENDENCIES ===================================================

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lint_rules:
    git: https://github.com/altynbek132/lint_rules
  test: ^1.25.8

  #
  #
  mobx_codegen:
    git:
      url: https://github.com/altynbek132/mobx.dart.git
      path: mobx_codegen

  injectable_generator: ^2.6.2
  build_runner: ^2.4.14
  mockito: ^5.4.5
  json_serializable: ^6.9.0
  freezed: ^2.5.7

  retrofit_generator: ^9.1.7

flutter:
  uses-material-design: true
